service: doc-bao-nhanh

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1  # Singapore region
  timeout: 30
  memorySize: 1024  # Tăng memory cho Puppeteer
  environment:
    NODE_ENV: production

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

package:
  patterns:
    - '!node_modules/chromium/**'
    - 'node_modules/aws-sdk/**'
    - 'node_modules/chrome-aws-lambda/**'
    - 'node_modules/puppeteer-core/**'
    - '!node_modules/puppeteer/**'
